### PR TITLE
format that sh*t

### PR DESCRIPTION
**Pull request by cantbeevil**
* added remapping to stop vscode from yelling at me all the time
* formatting via `forge fmt`

### CODE REVIEW

**Comment by kibagateaux** [comment]
Does this use all the default forge formatting rules? I dont see formatting config in the additions

**Comment by cantbeevil** [comment]
> Does this use all the default forge formatting rules? I dont see formatting config in the additions

@kibagateaux I didn't change config so it uses default. We might also want to add github workflow so it runs this command whenever PR gets created?

**Comment by kibagateaux** [comment]
1. Can you add the `forge fmt` command to `package.json` as a form of documentation please
2. we have a github action for running tests with forge in `.github/workflows`. We can probably reuse that flow but we want it run on all branches _besides_ master so that its formatted before we make a PR/merge. You can include that in this PR if you'd like or i can create a ticket for later

**Comment by mostarz93** [comment]
I think we can close this PR. Im addressing this in the pre-commit hook

**Pull request closed without merging**
