### PR TITLE
Update LineOfCredit.sol

### PR DESCRIPTION
**Pull request by BobZedF**
Clarifying code comment re accrueInterest() at request of cwalk + I added that the _accrue() also runs when rates are changed

### CODE REVIEW

**Comment by kibagateaux** [comment]
can you add the `-` symbol on new lines and align it with the `-` on the first line please.

**Comment by BobZedF** [comment]
Is this what you mean?
    /**
     * @dev -  Loops over all credit line ids and calls related internal functions during which InterestRateCredit is called 
                      with the id data and then 'interestAccrued' is updated.  
                      The related internal function _accrue() runs any time the balance on an individual credit line changes or if the 
                      interest rates of a credit line are changed by mutual consent between a Borrower and a Lender.
     */

**Comment by BobZedF** [comment]
> can you add the `-` symbol on new lines and align it with the `-` on the first line please.

Please see #158

**Comment by Seroxdesign** [comment]
LGTM

**Pull request merged**
